### PR TITLE
UNOMI-461: create a method for match calculation

### PR DESCRIPTION
**Pull request by liatiusim**

### CODE REVIEW

**Review by sergehuber — CHANGES_REQUESTED** [review]
Hi Liat, thanks for the PR, could you please create a JIRA ticket for this one and add an integration test ? Thanks.

**Comment by sergehuber** [comment]
@liatiusim did you see the previous question?

**Comment by sergehuber** [comment]
@liatiusim could you please update this ticket and create the JIRA and possibly an integration test ? If nothing is done I'll have to close this PR without merging.

**Comment by liatiusim** [comment]
Hey Serge, sorry for the late response.
Iv'e added a Jira task and updated the title of this PR. I'll add the itest soon

**Comment by sergehuber** [comment]
Thanks @liatiusim  !

**Comment by sergehuber** [comment]
@liatiusim I'll wait until you commit the integration test to review this in the final state. Thanks

**Comment by sergehuber** [comment]
Hello @liatiusim . After reviewing this once more I've decided to include it for the 1.5.5 release, you can add an integration test in a separate PR. Thank you.

**Review by sergehuber — APPROVED** [review]
This change is safe, I'll include it in 1.5.5. Thank you for the PR.

**Pull request merged**
