### PR TITLE
[UNOMI-645] - Add test for DataTable$Row.toString and DataTable.toString

### PR DESCRIPTION
**Pull request by lacinoire**
Hey 😊
I want to contribute a test.
Curious to hear what you think!

(I wrote this test as part of a research study at TU Delft. [Find out more](https://github.com/lacinoire/lacinoire/blob/main/README.md))

----

**Please** following this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/UNOMI) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
       -> I believe this to count as a trivial change
 - [x] Format the pull request title like `[UNOMI-XXX] - Title of the pull request`
 - [x] Provide integration tests for your changes, especially if you are changing the behavior of existing code or adding
       significant new parts of code.
       -> no new code, but providing tests 🙂
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why. 
       Copy the description to the related JIRA issue
 - [x] Run `mvn clean install -P integration-tests` to make sure basic checks pass. A more thorough check will be 
        performed on your pull request automatically.
        -> passes
 
Trivial changes like typos do not require a JIRA issue (javadoc, project build changes, small doc changes, comments...). 
 
If this is your first contribution, you have to read the [Contribution Guidelines](https://unomi.apache.org/contribute.html)
-> leads me to a 404 unfortunately :/
I have read the general contribution guidelines in other apache repositories.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by sergehuber** [comment]
Hello,

Thank you for your contribution. We require that pull requests are associated with a ticket in Unomi's JIRA. Could you please either create a ticket there or associate it to an existing one (if you can find a relevant one). You can find the Unomi JIRA here: https://issues.apache.org/jira/projects/UNOMI/summary

Best regards,
  Serge Huber.

**Comment by sergehuber** [comment]
Also, once you have created a ticket, please update the title of the PR to include the ticket number in the title. Thank you.

**Comment by lacinoire** [comment]
Unfortunately I can't access the JIRA under the link you gave me or the one from the issue template :/
The page just keeps loading & ends in a 'server took to long to respond' on both my Firefox and Chrome.
What is the trick to access it? 🙂


My issue would be very similar to the title of this PR:
Add a test case for DataTable$Row.toString and DataTable.toString, which are as far as I see not covered by another test yet.

**Comment by sergehuber** [comment]
Ok I've created the JIRA ticket : https://issues.apache.org/jira/browse/UNOMI-645 and merge your changes ! Thanks again for your contribution.

**Pull request merged**
