### PR TITLE
WIP: [UNOMI-66] Add kafka injector plugin

### PR DESCRIPTION
**Pull request by jbonofre**
It's not fully ready to be merged. I would like to add tests, documentation, etc. I'm working on it.

### CODE REVIEW

**Comment by sergehuber** [comment]
Thank you for the contribution. Looks good so far :) I was wondering if it would be possible to have a quick doc on how to set this up ? It could be in the manual or in a README.

**Comment by sergehuber** [comment]
Another way to do it is to merge this now and write the example later ? :)

**Comment by jbonofre** [comment]
Let me rebase and add new stuff around. Sorry for the delay.

**Comment by sergehuber** [comment]
Ok after discussion will merge and document separately.

**Comment by sergehuber** [comment]
Forgot to say thank you for the contribution !

**Comment by ArtioDev** [comment]
Hello,
I'm trying to configure the KafkaInjector plugin on Unomi to read message from kafka topic and ingest event into the CDP. 
Unfortunately at the moment I'm not been able to do that, could you help me ? Is there any documentation to follow ?

Thank you in advance,
Gianluca

**Pull request merged**
