### PR TITLE
Update to Karaf 4.2.x

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by jbonofre** [comment]
This is a work in progress, extracted from a bigger branch with lot of refactoring.

This is a minimum dependencies updates, I'm working on:

1. Adding the missing requirements/capabilities
2. Fix unomi overried in `bin/setenv` and `bin/karaf`.

**Comment by sergehuber** [comment]
Thank you so much ! I’ll review this ASAP !

**Comment by jbonofre** [comment]
@sergehuber hold on, I'm working on the PR during the week end (cherry picking from my "big refactoring" branch). I will let you know when it's ready for a first review round.

**Comment by sergehuber** [comment]
Ok I was wondering if it was complete :)

**Comment by jbonofre** [comment]
@sergehuber this is the minimum set to run on Karaf 4.2.x (including JDK11). I didn't test all (as it's cherry picked from a bigger branch as explained before), but at least it starts and expose `/cxs`.
I propose to quickly review this PR, then, I will do a second one with the refactoring (a bunch (almost all) of Unomi modules/bundles can be simplified and improved, it's what I started).

**Comment by sergehuber** [comment]
Thank you so much for doing this. It's funny because I had some of the changes due to the new Maven Bundle plugin also in my ES 7 branch. I'll test this asap and merge if ok !

**Comment by sergehuber** [comment]
Ok after some tests all looks good. The only remaining issue is compiling with JDK 11 but I think we can handle this seperately.

**Pull request merged**
