### PR TITLE
UNOMI-616: Update GraphQL Playground to the latest version or switch …

### PR DESCRIPTION
**Pull request by anatol-sialitski**
[UNOMI-616](https://issues.apache.org/jira/browse/UNOMI-616) - Update GraphQL Playground to the latest version or switch to GraphiQL

Switched from GraphQL Playground to GraphiQL Playground v3.3.1
Module `unomi-graphql-playground` was renamed to `unomi-graphql-ui`

### CODE REVIEW

**Comment by anatol-sialitski** [comment]
@sergehuber Did you have the time to look at my PR?

**Comment by sergehuber** [comment]
Could you fix the conflict @anatol-sialitski and then I'll test it ?

**Comment by anatol-sialitski** [comment]
@sergehuber done, please have a look at

**Review by sergehuber — APPROVED** [review]
Thank you for the changes, looks good to me !

**Pull request merged**
