### PR TITLE
Update to Apache Karaf Cellar 4.2.1

### PR DESCRIPTION
**Pull request by shirbr**

### CODE REVIEW

**Comment by jbonofre** [comment]
-1 for now, I would rather update to Cellar 4.2.1 (that will be released very soon). I found a feature sync issue on Cellar 4.2.0.

**Comment by sergehuber** [comment]
@jbonofre could you mark the PR as requesting changes then ?

**Comment by jbonofre** [comment]
Cellar 4.2.1 has been released, we can upgrade to this version in Unomi.

**Comment by jbonofre** [comment]
@shirbr do you want to update this PR or you want me to create a new PR ? Thanks !

**Comment by shirbr** [comment]
Updated the pom.xml to use 4.2.1
Thanks

**Review by jbonofre — APPROVED** [review]

**Comment by jbonofre** [comment]
I will squash and merge once I fully tested.

**Pull request merged**
