### PR TITLE
UNOMI-473-use name for path to location if exists, like in GeoLocationByPointSe…

### PR DESCRIPTION
**Pull request by giladw**
…ssionConditionESQueryBuilder

PR Title format: 

    [UNOMI-XXX] Pull request title with JIRA reference

**Please** add a meaningful description for your change here

----

**Please** following this checklist to help us incorporate your contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/UNOMI) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
 - [x] Format the pull request title like `[UNOMI-XXX] - Title of the pull request`
 - [ ] Provide integration tests for your changes, especially if you are changing the behavior of existing code or adding
       significant new parts of code.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why. 
       Copy the description to the related JIRA issue
 - [x] Run `mvn clean install -P integration-tests` to make sure basic checks pass. A more thorough check will be 
        performed on your pull request automatically.
 
Trivial changes like typos do not require a JIRA issue (javadoc, project build changes, small doc changes, comments...). 
 
If this is your first contribution, you have to read the [Contribution Guidelines](https://unomi.apache.org/contribute.html)

If your pull request is about ~20 lines of code you don't need to sign an [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) 
if you are unsure please ask on the developers list.

To make clear that you license your contribution under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by sergehuber** [comment]
Hi @giladw could you add the JIRA ticket to the PR title to make it easier to cross reference ? Thank you

**Comment by giladw** [comment]
@sergehuber  edited the title of the pr

**Review by dgriffon — COMMENTED** [review]
It would have been great to document it somewhere as no one can know about that name parameter unless looking at the code .. (it's the same for [GeoLocationByPointSessionConditionESQueryBuilder](https://github.com/apache/unomi/blob/master/plugins/baseplugin/src/main/java/org/apache/unomi/plugins/baseplugin/conditions/GeoLocationByPointSessionConditionESQueryBuilder.java#L32))

**Review by dgriffon — APPROVED** [review]

**Comment by dgriffon** [comment]
Can you please provide a scenario, or more detail on how to use that parameter in the JIRA ticket? Thank you

**Pull request merged**
