### PR TITLE
UNOMI-616 - Update GraphQL Playground to the latest version or switch to GraphiQL

### PR DESCRIPTION
**Pull request by anatol-sialitski**
[UNOMI-616](https://issues.apache.org/jira/browse/UNOMI-616) - Update GraphQL Playground to the latest version or switch to GraphiQL

Switched from GraphQL Playground to GraphiQL Playground v3.0.6

### CODE REVIEW

**Review by sergehuber — CHANGES_REQUESTED** [review]
Hi Anatol, 

Thank you very much for the PR, I just think we should rename the project from graphql-playground to graphql-ui what do you think ? 

Regards,
  Serge...

**Review by sergehuber — APPROVED** [review]
Hi Anatol, 

Thank you very much for the changes. I approved the PR.

Regards,
  Serge...

**Comment by sergehuber** [comment]
I think that before merging we should analyze what is making the tests fail. @anatol-sialitski could you look into it ? Thanks.

**Comment by sergehuber** [comment]
I tried running the tests locally and it seems there is an error while trying to install the GraphQL feature : 

Here's the log from the console : 

Fri May 17 14:45:59 CEST 2024: Finish execution of: {version=2.4.0, name='viewEventPagePath', bundle=org.apache.unomi.shell-commands}
Fri May 17 14:45:59 CEST 2024: Migration step: migrationStatus reach: STARTED
Fri May 17 14:45:59 CEST 2024: Migration step: migrationStatus reach: COMPLETED

unomi:start
[2024-05-17T14:46:01,492][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [shuber-macbook.local] updating index lifecycle policy [context-unomi-rollover-policy]
Installing feature cdp-graphql-feature

and from the logs : 

2024-05-17T14:47:18,897 | ERROR | pool-13-thread-1 | BundleWatcherImpl                | 218 - org.apache.unomi.lifecycle-watcher - 2.5.0.SNAPSHOT |  Error when installing cdp-graphql-feature feature 
java.lang.InterruptedException: null
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:418) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:190) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvisionInThread(FeaturesServiceImpl.java:1002) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvisionInThread(FeaturesServiceImpl.java:972) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:820) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeatures(FeaturesServiceImpl.java:740) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.installFeature(FeaturesServiceImpl.java:725) ~[?:?]
        at Proxy39f04bd5_537b_4211_9f8f_6b3888df90c2.installFeature(Unknown Source) ~[?:?]
        at org.apache.unomi.lifecycle.BundleWatcherImpl.lambda$installFeatures$3(BundleWatcherImpl.java:290) [!/:?]
        at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698) [?:?]
        at org.apache.unomi.lifecycle.BundleWatcherImpl.installFeatures(BundleWatcherImpl.java:285) [!/:?]
        at org.apache.unomi.lifecycle.BundleWatcherImpl.access$500(BundleWatcherImpl.java:58) [!/:?]
        at org.apache.unomi.lifecycle.BundleWatcherImpl$2.run(BundleWatcherImpl.java:319) [!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2024-05-17T14:47:18,903 | INFO  | features-3-thread-1 | FeaturesServiceImpl              | 13 - org.apache.karaf.features.core - 4.2.15 |    wrap_file__Users_loom_.m2_repository_org_codehaus_mojo_animal-sniffer-annotations_1.14_animal-sniffer-annotations-1.14.jar/0.0.0 
2024-05-17T14:47:18,903 | WARN  | pool-13-thread-1 | BundleWatcherImpl                | 218 - org.apache.unomi.lifecycle-watcher - 2.5.0.SNAPSHOT |  The bundle org.apache.unomi.cdp-graphql-api-impl is in not active, some errors could happen when using the application 
2024-05-17T14:47:18,904 | WARN  | pool-13-thread-1 | BundleWatcherImpl                | 218 - org.apache.unomi.lifecycle-watcher - 2.5.0.SNAPSHOT |  The bundle org.apache.unomi.unomi-graphql-ui is in not active, some errors could happen when using the application

**Comment by anatol-sialitski** [comment]
This has been done in the new PR https://github.com/apache/unomi/pull/681

**Pull request closed without merging**
